### ISSUE TITLE
v1 branch or tag

### ISSUE THREAD

**Issue by anatawa12** [snow-actions/git-config-user#14]
I want to use latest version of this action with `snow-actions/git-config-user@v1`.

**Comment by SnowCait** [comment]
Hi,

Thank you for the issue.

I don't recommend to use `v1` because it may break your workflow even if you don't anything.
I recommend to use [Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot) or [Renovate](https://github.com/marketplace/renovate) to update version.

However, GitHub recommend to use it to keep version up-to-date.
I'll consider to create `v1` branch. (Tag once created shouldn't be updated.)

**Comment by SnowCait** [comment]
There were no version update over the past year. I will reconsider if required.
